# Generated by Django 5.0.2 on 2024-04-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_propietario', models.IntegerField(blank=True, null=True)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('nombre_admin', models.CharField(max_length=40)),
                ('apellido_admin', models.CharField(max_length=40)),
                ('contrasena_admin', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=75)),
                ('telefono', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=75)),
                ('redes_sociales', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=14, null=True)),
                ('correo', models.EmailField(max_length=75)),
                ('direccion', models.CharField(max_length=75)),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('especializacion', models.CharField(blank=True, max_length=40, null=True)),
                ('horarios', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena', models.CharField(max_length=40)),
                ('ficha_de_ingreso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(max_length=14)),
                ('contrasena', models.CharField(max_length=40)),
                ('inscripcion', models.BooleanField(default=False)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_registro.coach')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rutina', models.TextField()),
                ('dieta', models.TextField()),
                ('pago_membresia', models.BooleanField(default=False, null=True)),
                ('horarios', models.CharField(blank=True, max_length=20, null=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_registro.coach')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_registro.userregistration')),
            ],
        ),
    ]
