# Generated by Django 5.0.2 on 2024-04-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_propietario', models.CharField(max_length=7)),
                ('documento', models.CharField(max_length=10)),
                ('nombre_admin', models.CharField(max_length=15, unique=True)),
                ('apellido_admin', models.CharField(max_length=30)),
                ('contrasena_admin', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=75)),
                ('telefono', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=75)),
                ('redes_sociales', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=75)),
                ('direccion', models.CharField(max_length=75)),
                ('experiencia', models.IntegerField()),
                ('conocimiento', models.TextField()),
                ('horario_de_entrada', models.TimeField(null=True)),
                ('horario_de_salida', models.TimeField(null=True)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=40)),
                ('redes_sociales', models.URLField(blank=True, null=True)),
                ('ficha_de_ingreso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('rutina_diaria', models.TextField()),
                ('complicaciones', models.TextField()),
                ('rendimiento', models.TextField()),
                ('dieta', models.TextField()),
                ('faltas', models.IntegerField()),
                ('pago_membresia', models.BooleanField(default=False)),
                ('avances', models.TextField()),
                ('horario_asignado', models.CharField(max_length=100)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_registro.entrenador')),
            ],
        ),
    ]
