# Generated by Django 5.0.2 on 2024-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, '---------'), (2, 'Masculino'), (3, 'Femenino'), (4, 'Otro')], null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='turno',
            field=models.IntegerField(blank=True, choices=[(1, '-----'), (2, 'Noche'), (3, 'Dia')], null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='typo_id',
            field=models.IntegerField(blank=True, choices=[(1, '-------'), (2, 'Fitness'), (3, 'Pilates'), (4, 'Rehabilitacion fisica'), (5, 'Plan para mayores'), (6, 'Yoga'), (7, 'Gimnasia')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], null=True),
        ),
    ]
