# Generated by Django 5.0.2 on 2024-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientroutine',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
