# Generated by Django 5.0.2 on 2024-04-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='typo_id',
            field=models.IntegerField(choices=[(1, 'Fitness'), (2, 'Pilates'), (3, 'Rehabilitacion fisica'), (4, 'Plan para mayores'), (5, 'Yoga'), (6, 'Gimnasia')]),
        ),
    ]
