# Generated by Django 5.0.2 on 2024-04-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0002_alter_coach_genero_alter_coach_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='gym_registro.admin'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='gym_registro.user'),
        ),
    ]
