# Generated by Django 5.0.2 on 2024-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0002_alter_clientroutine_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientroutine',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='clientroutine',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientroutine',
            name='pago_membresia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
