# Generated by Django 5.0.2 on 2024-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0002_alter_coach_typo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='especializacion',
        ),
        migrations.AlterField(
            model_name='coach',
            name='typo_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Fitness'), (2, 'Pilates'), (3, 'Rehabilitacion fisica'), (4, 'Plan para mayores'), (5, 'Yoga'), (6, 'Gimnasia')], null=True),
        ),
    ]
