# Generated by Django 5.0.2 on 2024-04-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_registro', '0003_alter_coach_admin_alter_coach_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudescliente',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_clientes', to='gym_registro.admin'),
        ),
        migrations.AlterField(
            model_name='solicitudescliente',
            name='estatura',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='solicitudescliente',
            name='peso',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
